// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/realityone/bro-mirror/internal/conf"
	"github.com/realityone/bro-mirror/internal/server"
	"github.com/realityone/bro-mirror/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, data *conf.Data, mirror *conf.Mirror, logger log.Logger) (*kratos.App, func(), error) {
	serviceMirror, err := service.NewMirror(mirror, logger)
	if err != nil {
		return nil, nil, err
	}
	resolveService := service.NewResolveService(serviceMirror)
	repositoryService := service.NewRepositoryService(serviceMirror)
	repositoryCommitService := service.NewRepositoryCommitService(serviceMirror)
	handler, err := server.NewConnectHandler(confServer, serviceMirror, resolveService, repositoryService, repositoryCommitService, logger)
	if err != nil {
		return nil, nil, err
	}
	connectServer, err := server.NewConnectServer(confServer, handler)
	if err != nil {
		return nil, nil, err
	}
	app := newApp(logger, connectServer)
	return app, func() {
	}, nil
}
